#!/bin/bash
# Bibliography: http://www.linux-kvm.org/page/Networking
set -x

switch=br0

if [ -n "$1" ]; then
        sudo tunctl -u `whoami` -t $1
        sudo ip link set $1 up
        sleep 0.5s
        sudo brctl addif $switch $1
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi
