#!/bin/bash
#
# Calin-Andrei Burloiu, 2010, calin.burloiu@gmail.com
#
# This script converts an MTS file into an AVI file, which 
# contains an H.264 video stream and and an MP3 audio stream.
#

if test $# -ne 4; then
    echo "Usage: $0 mts-file ts-file bitrate resolution"
    exit 1
fi

MTS_FILE="$1"
TS_FILE="$2"
BITRATE="$3"
RESOLUTION="$4"
FFMPEG=/usr/bin/ffmpeg

if test ! -f "$MTS_FILE"; then
    echo "Error: No such: file $MTS_FILE"
    exit 1
fi

$FFMPEG -i "$MTS_FILE" -f mpegts -acodec libmp3lame -ab 128k -ar 44100 -ac 2 -vcodec libx264 -vpre normal -b "$BITRATE" -r 25 -s $RESOLUTION -threads 0 "$TS_FILE"
