#!/bin/bash
#
# 2010, Calin-Andrei Burloiu, calin.burloiu@gmail.com
#
# This scripts creates thumbnails for all videos with a specified suffix.
# 
#

if [ $# -ne 2 ]; then
	echo "usage: $0 root_path suffix"
	exit 1
fi

root_path="$1"
suffix="$2"

(
IFS=$'\n'
for filename in $(find "$root_path" -name "*$suffix"); do
	new_filename=$(dirname "$filename")/$(basename "$filename" "$suffix")_tmp.jpg
	new_filename1=$(dirname "$filename")/$(basename "$filename" "$suffix")_small.jpg
	new_filename2=$(dirname "$filename")/$(basename "$filename" "$suffix")_big.jpg
	./ffmpeg-extract-thumbnail "$filename" "$new_filename" 1280x720
        if [ ! -e "$new_filename1" ]; then
            ffmpeg -i "$new_filename" -s 122x69 -f image2 "$new_filename1"
        fi
        if [ ! -e "$new_filename2" ]; then
            ffmpeg -i "$new_filename" -s 149x84 -f image2 "$new_filename2"
        fi
	rm -f "$new_filename"
done
)
